name: React CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
  
    - name: Install Packages
      run: npm install
       
    - name: Build page
      run: npm run build
      
    - name: Install Surge
      run: npm install -g surge
      
    - name: Run surge
      run: surge ./build https://diaries-app-muhib.surge.sh --token ${{secrets.SURGE_SECRET}}
